services:
  mysql:
    image: mysql:8.2
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./sql:/home/sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
